"""Pydantic models for API requests and responses"""
from pydantic import BaseModel, Field
from typing import List, Optional


class CategoryAttribute(BaseModel):
    """Facial attribute selection from user"""
    category: str = Field(..., description="e.g., 'nose', 'eyes', 'mouth'")
    attribute: str = Field(..., description="e.g., 'color', 'size', 'shape'")
    value: str = Field(..., description="e.g., 'brown', 'large', 'round'")


class CaptionRequest(BaseModel):
    """Request to generate caption from user attributes"""
    attributes: List[CategoryAttribute] = Field(..., description="List of selected facial attributes")
    description: Optional[str] = Field(default="", description="Optional additional description")


class CaptionResponse(BaseModel):
    """Response containing generated dense prompt"""
    dense_prompt: str = Field(..., description="Dense prompt generated by LLaVa")
    original_input: CaptionRequest = Field(..., description="Original user input")
    message: Optional[str] = Field(default="", description="API response message")


class ImageGenerationRequest(BaseModel):
    """Request to generate image from prompt"""
    prompt: str = Field(..., description="Text prompt for image generation")
    height: int = Field(default=512, ge=256, le=1024, description="Image height in pixels")
    width: int = Field(default=512, ge=256, le=1024, description="Image width in pixels")
    num_inference_steps: int = Field(default=50, ge=1, le=100, description="Number of denoising steps")
    guidance_scale: float = Field(default=7.5, ge=0, le=20, description="Guidance scale for classifier-free guidance")


class ImageGenerationResponse(BaseModel):
    """Response containing generated image"""
    image_base64: Optional[str] = Field(default=None, description="Generated image in base64 format (can be empty for test)")
    prompt: str = Field(..., description="Prompt used for generation")
    generation_time: float = Field(..., description="Time taken to generate image in seconds")
    message: Optional[str] = Field(default="", description="API response message")
    image_path: Optional[str] = Field(default=None, description="Local path where image was saved")
